[package]
name = "vst3-host-boilerplate"
version = "0.1.0"
authors = ["m-hilgendorf <mike@hilgendorf.audio>"]
edition = "2018"

[dependencies]
vst3-derive = { path = "../vst3-derive" }
vst3-impl = { path = "../vst3-impl" }
vst3-interfaces= { path = "../vst3-interfaces" }
widestring = "0.4.0"